/**
 * Writes `src/agent-session/providers/well-known-models.gen.ts`: what is known of each well-known
 * model, as `const` data, so that a model's settings can be typed from it.
 *
 * Two sources are merged. models.dev's catalog (https://models.dev/api.json) gives each model's
 * context window, output limit, kinds of input and price. `well-known-models.measured.json` names
 * the models to include, by provider, and for each holds what was measured against the provider
 * and is not in the catalog, or differs from it: the reasoning efforts it takes, the kinds of input
 * it took when sent them, and the price of an hour-long cache write. What was measured wins.
 *
 *   bun run models:refresh              # from models.dev
 *   bun run models:refresh <api.json>   # from a copy of the catalog
 */

import { readFileSync, writeFileSync } from "node:fs";

type Json = Record<string, unknown>;

const measuredPath = "src/agent-session/providers/well-known-models.measured.json";
const generatedPath = "src/agent-session/providers/well-known-models.gen.ts";

const [from] = process.argv.slice(2);
const catalog = (from === undefined ? await fetch("https://models.dev/api.json").then((response) => response.json()) : JSON.parse(readFileSync(from, "utf8"))) as Record<
  string,
  { models: Record<string, { limit: { context: number; output: number }; modalities: { input: Array<string> }; cost: Json }> }
>;
const measured = JSON.parse(readFileSync(measuredPath, "utf8")) as Record<string, Record<string, { efforts?: Array<string>; input?: Array<string>; price?: Json }>>;

/** A catalog price in this harness's names; its first tier is the price above that tier's context. */
function price(cost: Json): Json {
  const rate = (from: Json): Json => ({
    input: from["input"],
    output: from["output"],
    ...(from["cache_read"] === undefined ? {} : { cacheRead: from["cache_read"] }),
    ...(from["cache_write"] === undefined ? {} : { cacheWrite: from["cache_write"] }),
  });
  const tier = (cost["tiers"] as Array<Json & { tier: { size: number } }> | undefined)?.[0];
  return { ...rate(cost), ...(tier === undefined ? {} : { above: { context: tier.tier.size, ...rate(tier) } }) };
}

const missing: Array<string> = [];
const models = Object.fromEntries(
  Object.entries(measured).map(([provider, listed]) => [
    provider,
    Object.fromEntries(
      Object.entries(listed).flatMap(([model, ours]) => {
        const theirs = catalog[provider]?.models[model];
        if (theirs === undefined) {
          missing.push(`${provider}/${model}`);
          return [];
        }
        const { above, ...base } = price(theirs.cost) as Json & { above?: Json };
        return [
          [
            model,
            {
              context: theirs.limit.context,
              output: theirs.limit.output,
              input: ours.input ?? theirs.modalities.input,
              ...(ours.efforts === undefined ? {} : { efforts: ours.efforts }),
              price: { ...base, ...ours.price, ...(above === undefined ? {} : { above }) },
            },
          ],
        ];
      }),
    ),
  ]),
);
if (missing.length > 0) throw new Error(`The catalog does not list: ${missing.join(", ")}`);

const counted = Object.entries(models).map(([provider, listed]) => `${provider} ${Object.keys(listed).length}`);
writeFileSync(
  generatedPath,
  [
    "// Generated by `bun scripts/models/refresh.ts` from models.dev's catalog and",
    "// `well-known-models.measured.json`. Change those, not this file.",
    "",
    `export const wellKnownModels = ${JSON.stringify(models, null, 2)} as const;`,
    "",
  ].join("\n"),
);
console.log(`wrote ${generatedPath}: ${counted.join(", ")}`);
