// Generated by `bun scripts/models/refresh.ts` from models.dev's catalog. Change that script, not this file.

import type { Capabilities } from "./well-known-models.ts";

/** What models.dev's catalog says of each model that is not well-known, by provider. */
export const catalogModels: Readonly<Record<string, Readonly<Record<string, Capabilities>>>> = {
  "anthropic": {
    "claude-opus-4-5": {
      "context": 200000,
      "output": 64000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    },
    "claude-sonnet-4-5": {
      "context": 200000,
      "output": 64000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 3,
        "output": 15,
        "cacheRead": 0.3,
        "cacheWrite": 3.75
      }
    },
    "claude-opus-4-5-20251101": {
      "context": 200000,
      "output": 64000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    },
    "claude-opus-5": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    },
    "claude-fable-5": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 10,
        "output": 50,
        "cacheRead": 1,
        "cacheWrite": 12.5
      }
    },
    "claude-opus-4-8": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    },
    "claude-sonnet-4-5-20250929": {
      "context": 200000,
      "output": 64000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 3,
        "output": 15,
        "cacheRead": 0.3,
        "cacheWrite": 3.75
      }
    },
    "claude-sonnet-5": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 2,
        "output": 10,
        "cacheRead": 0.2,
        "cacheWrite": 2.5
      }
    },
    "claude-opus-4-6": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "max"
      ],
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    },
    "claude-haiku-4-5-20251001": {
      "context": 200000,
      "output": 64000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 1,
        "output": 5,
        "cacheRead": 0.1,
        "cacheWrite": 1.25
      }
    },
    "claude-sonnet-4-6": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "max"
      ],
      "budget": {
        "min": 1024
      },
      "price": {
        "input": 3,
        "output": 15,
        "cacheRead": 0.3,
        "cacheWrite": 3.75
      }
    },
    "claude-opus-4-7": {
      "context": 1000000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 5,
        "output": 25,
        "cacheRead": 0.5,
        "cacheWrite": 6.25
      }
    }
  },
  "openai": {
    "gpt-3.5-turbo": {
      "context": 16385,
      "output": 4096,
      "input": [
        "text"
      ],
      "reasoning": false,
      "price": {
        "input": 0.5,
        "output": 1.5,
        "cacheRead": 0
      }
    },
    "text-embedding-3-small": {
      "context": 8191,
      "output": 1536,
      "input": [
        "text"
      ],
      "reasoning": false,
      "price": {
        "input": 0.02,
        "output": 0
      }
    },
    "gpt-realtime-2.1": {
      "context": 128000,
      "output": 32000,
      "input": [
        "text",
        "audio",
        "image"
      ],
      "reasoning": true,
      "efforts": [
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "price": {
        "input": 4,
        "output": 24,
        "cacheRead": 0.4
      }
    },
    "gpt-4o-2024-05-13": {
      "context": 128000,
      "output": 4096,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 5,
        "output": 15
      }
    },
    "gpt-4o": {
      "context": 128000,
      "output": 16384,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": false,
      "price": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25
      }
    },
    "gpt-image-2": {
      "context": 0,
      "output": 0,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 5,
        "output": 30,
        "cacheRead": 1.25
      }
    },
    "o4-mini": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text",
        "image"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.275
      }
    },
    "o3-mini": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.55
      }
    },
    "text-embedding-ada-002": {
      "context": 8192,
      "output": 1536,
      "input": [
        "text"
      ],
      "reasoning": false,
      "price": {
        "input": 0.1,
        "output": 0
      }
    },
    "gpt-4": {
      "context": 8192,
      "output": 8192,
      "input": [
        "text"
      ],
      "reasoning": false,
      "price": {
        "input": 30,
        "output": 60
      }
    },
    "gpt-4.1-nano": {
      "context": 1047576,
      "output": 32768,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 0.1,
        "output": 0.4,
        "cacheRead": 0.025
      }
    },
    "gpt-5.6": {
      "context": 1050000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 4,
        "output": 20,
        "cacheRead": 0.4,
        "cacheWrite": 5,
        "above": {
          "context": 272000,
          "input": 8,
          "output": 30,
          "cacheRead": 0.8,
          "cacheWrite": 10
        }
      }
    },
    "o1": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 15,
        "output": 60,
        "cacheRead": 7.5
      }
    },
    "gpt-5.3-codex-spark": {
      "context": 128000,
      "output": 32000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "price": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175
      }
    },
    "text-embedding-3-large": {
      "context": 8191,
      "output": 3072,
      "input": [
        "text"
      ],
      "reasoning": false,
      "price": {
        "input": 0.13,
        "output": 0
      }
    },
    "gpt-4o-2024-08-06": {
      "context": 128000,
      "output": 16384,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25
      }
    },
    "gpt-4o-mini": {
      "context": 128000,
      "output": 16384,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": false,
      "price": {
        "input": 0.15,
        "output": 0.6,
        "cacheRead": 0.075
      }
    },
    "o3-pro": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text",
        "image"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 20,
        "output": 80
      }
    },
    "gpt-daybreak-blue-latest": {
      "context": 1050000,
      "output": 128000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 4,
        "output": 20,
        "cacheRead": 0.4,
        "cacheWrite": 5,
        "above": {
          "context": 272000,
          "input": 8,
          "output": 30,
          "cacheRead": 0.8,
          "cacheWrite": 10
        }
      }
    },
    "gpt-4.1": {
      "context": 1047576,
      "output": 32768,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": false,
      "price": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5
      }
    },
    "gpt-4o-2024-11-20": {
      "context": 128000,
      "output": 16384,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25
      }
    },
    "gpt-4.1-mini": {
      "context": 1047576,
      "output": 32768,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": false,
      "price": {
        "input": 0.4,
        "output": 1.6,
        "cacheRead": 0.1
      }
    },
    "gpt-4-turbo": {
      "context": 128000,
      "output": 4096,
      "input": [
        "text",
        "image"
      ],
      "reasoning": false,
      "price": {
        "input": 10,
        "output": 30
      }
    },
    "gpt-daybreak-red-latest": {
      "context": 400000,
      "output": 128000,
      "input": [
        "text",
        "image"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "price": {
        "input": 12.5,
        "output": 75,
        "cacheRead": 1.25,
        "cacheWrite": 15.625
      }
    },
    "o3": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5
      }
    },
    "o1-pro": {
      "context": 200000,
      "output": 100000,
      "input": [
        "text",
        "image"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 150,
        "output": 600
      }
    }
  },
  "xai": {
    "grok-4.3": {
      "context": 1000000,
      "output": 30000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "none",
        "low",
        "medium",
        "high"
      ],
      "price": {
        "input": 1.25,
        "output": 2.5,
        "cacheRead": 0.2,
        "above": {
          "context": 200000,
          "input": 2.5,
          "output": 5,
          "cacheRead": 0.4
        }
      }
    },
    "grok-4.20-0309-reasoning": {
      "context": 1000000,
      "output": 30000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [],
      "price": {
        "input": 1.25,
        "output": 2.5,
        "cacheRead": 0.2,
        "above": {
          "context": 200000,
          "input": 2.5,
          "output": 5,
          "cacheRead": 0.4
        }
      }
    },
    "grok-4.20-0309-non-reasoning": {
      "context": 1000000,
      "output": 30000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": false,
      "price": {
        "input": 1.25,
        "output": 2.5,
        "cacheRead": 0.2,
        "above": {
          "context": 200000,
          "input": 2.5,
          "output": 5,
          "cacheRead": 0.4
        }
      }
    },
    "grok-4.20-multi-agent-0309": {
      "context": 1000000,
      "output": 30000,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "reasoning": true,
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ],
      "price": {
        "input": 1.25,
        "output": 2.5,
        "cacheRead": 0.2,
        "above": {
          "context": 200000,
          "input": 2.5,
          "output": 5,
          "cacheRead": 0.4
        }
      }
    }
  }
};
