/**
 * The well-known models: what is known of each (`Capabilities`), and a model's settings as a type.
 *
 * The data is `well-known-models.gen.ts`, generated by `bun scripts/models/refresh.ts` from two
 * sources. models.dev's catalog gives each model's context window, output limit, kinds of input,
 * price in US dollars per million tokens (`above` is the price of a request whose input is over its
 * `context`), whether it reasons, and how its reasoning is set: the efforts it takes, or a budget of
 * thinking tokens. `well-known-models.measured.json` names the models (each provider's latest frontier
 * models, and xAI's fast coding model grok-build-0.1, alias grok-code-fast-1, as Claude Haiku is
 * Anthropic's) and holds what was measured against the providers (2026-10-01) and is not in the
 * catalog:
 *
 * - PDF input for ten GPT-5 models the catalog lists as taking none (each read one when sent it);
 * - Anthropic's hour-long cache writes, at twice the input price (the catalog has the five-minute rate);
 * - the thinking modes a model takes besides the provider's default and `disabled`: Claude Sonnet 5.5
 *   thinks only between tool calls on request (`thinking: ["between_tools"]`).
 *
 * Where a provider takes efforts that the catalog does not list (xAI's models took `minimal` when
 * asked, 2026-10-01), a user's configuration overrides the catalog (`ModelOverrides`; the
 * configuration's `models:`, as `src/agent-config/fixtures/user/40_models.yml` shows).
 *
 * Also measured: Anthropic refuses `max_tokens` above a model's output (Haiku 4.5: 64,000); OpenAI
 * accepts any `max_output_tokens`, so its limit cannot be read from a refusal.
 *
 * A model is found by its name or by its name with a release date after it
 * (`claude-haiku-4-5-20251001` is `claude-haiku-4-5`; `gpt-5-mini` is not `gpt-5`). A model that is
 * not well-known (a local server's) is known by what its host provides (`KnownModels`), at run time.
 */

import { Context, Effect, Schema } from "effect";
import type { ModelName, ProviderName } from "../../agent-machine/names.ts";
import { Effort, type ModelSettings, type ThinkingMode } from "../../agent-machine/settings.ts";
import { firstAnswer } from "../first-answer.ts";
import { wellKnownModels } from "./well-known-models.gen.ts";

export interface Price {
  readonly input: number;
  readonly output: number;
  readonly cacheRead?: number;
  readonly cacheWrite?: number;
  readonly cacheWrite1h?: number;
}

/** The efforts that models.dev names: `none`, which turns reasoning off, then the core's efforts. */
export const KnownEffort = Schema.Literals(["none", ...Effort.literals]);
export type KnownEffort = typeof KnownEffort.Type;

/** A thinking mode that a model takes besides the provider's default and `disabled`, as measured: models.dev does not record it. */
export const KnownThinking = Schema.Literals(["between_tools"]);
export type KnownThinking = typeof KnownThinking.Type;

/**
 * What is known of a model: what it accepts and what it costs. A request is shaped to it: a setting
 * outside what the model accepts is sent as the nearest value it does accept (an effort above its
 * highest, as its highest), or not sent.
 */
export interface Capabilities {
  /** The maximum number of context tokens that the model accepts, when known. */
  readonly context?: number;
  /** The maximum number of tokens that the model writes in one response, when known. */
  readonly output?: number;
  /** The kinds of input that it accepts: `text`, `image`, `pdf`. */
  readonly input: ReadonlyArray<string>;
  /** Whether it reasons, when known. */
  readonly reasoning?: boolean;
  /** The reasoning efforts that it accepts, least first, when known; `none` turns its reasoning off. */
  readonly efforts?: ReadonlyArray<KnownEffort>;
  /** The thinking modes that it takes besides the provider's default and `disabled`, as measured. */
  readonly thinking?: ReadonlyArray<KnownThinking>;
  /** The budget of thinking tokens that it takes in place of efforts, when it takes one: at least `min`, and at most `max` when known. */
  readonly budget?: { readonly min: number; readonly max?: number };
  readonly price: Price & { readonly above?: Price & { readonly context: number } };
}

const known: Readonly<Record<string, Readonly<Record<string, Capabilities>>>> = wellKnownModels;

/** Whether `model` is `name` followed by a release date: `-2025-08-07` (OpenAI) or `-20251001` (Anthropic). */
const datedFrom = (name: string, model: string): boolean =>
  model.startsWith(`${name}-`) && /^(\d{4}-\d{2}-\d{2}|\d{8})$/.test(model.slice(name.length + 1));

/** Returns what is known of the well-known `model` of `provider`, found by its name or a dated name. */
export function capabilitiesOf(provider: ProviderName | string, model: ModelName | string): Capabilities | undefined {
  const models = known[provider] ?? {};
  const name = model in models ? model : Object.keys(models).find((each) => datedFrom(each, model));
  return name === undefined ? undefined : models[name];
}

/** One source's answer for a model: its capabilities, or `undefined` when the source does not know it. */
export type ModelKnowledge = (provider: ProviderName, model: ModelName) => Effect.Effect<Capabilities | undefined>;

/** The well-known models. */
export const wellKnown: ModelKnowledge = (provider, model) => Effect.succeed(capabilitiesOf(provider, model));

/**
 * The sources of what is known of each model, asked in order; the first that knows a model answers
 * (`firstAnswer`). Whoever chooses the model for a request reads it (`ModelFromFacts` puts it on the
 * request's target). By default, the well-known models; a host that knows more (a local server that
 * reports what its models accept) puts its own source first.
 */
export const KnownModels = Context.Reference<ReadonlyArray<ModelKnowledge>>("agent-session/KnownModels", { defaultValue: () => [wellKnown] });

const Count = Schema.Int.check(Schema.isGreaterThanOrEqualTo(1));

/**
 * What a user's configuration says of one model (`models:`, by `provider/model`), over what is known
 * of it. Each field given replaces the known field whole; a field not given stays as known.
 */
export const ModelOverride = Schema.Struct({
  context: Schema.optionalKey(Count),
  output: Schema.optionalKey(Count),
  input: Schema.optionalKey(Schema.Array(Schema.String)),
  reasoning: Schema.optionalKey(Schema.Boolean),
  efforts: Schema.optionalKey(Schema.Array(KnownEffort)),
  thinking: Schema.optionalKey(Schema.Array(KnownThinking)),
  budget: Schema.optionalKey(Schema.Struct({ min: Count, max: Schema.optionalKey(Count) })),
});
export type ModelOverride = typeof ModelOverride.Type;

/** The user's overrides, by `provider/model`; none unless a host provides them from its configuration. */
export const ModelOverrides = Context.Reference<ReadonlyMap<string, ModelOverride>>("agent-session/ModelOverrides", { defaultValue: () => new Map() });

/**
 * Returns `sources` with `overrides` applied: a model that an override names has the first answer of
 * `sources` with the override's fields over it. A model that no source knows takes the override's
 * fields alone, accepting no files and costing nothing, as a model of which nothing is known does.
 */
export const withOverrides = (overrides: ReadonlyMap<string, ModelOverride>, sources: ReadonlyArray<ModelKnowledge>): ReadonlyArray<ModelKnowledge> =>
  overrides.size === 0
    ? sources
    : [
        (provider, model) =>
          Effect.map(firstAnswer(sources.map((source) => source(provider, model))), (known) => {
            const override = overrides.get(`${provider}/${model}`);
            return override === undefined ? known : { ...(known ?? { input: [], price: { input: 0, output: 0 } }), ...override };
          }),
      ];

/** Returns what is known of `model` of `provider`: the first answer of `KnownModels`. */
export const knownCapabilities = (provider: ProviderName, model: ModelName): Effect.Effect<Capabilities | undefined> =>
  Effect.gen(function* () {
    const sources = yield* KnownModels;
    return yield* firstAnswer(sources.map((source) => source(provider, model)));
  });

/**
 * The efforts that a model which takes a thinking budget in place of an effort (Claude Haiku 4.5)
 * takes: its provider's adapter sends each as a budget, `low` as the least budget it takes.
 */
export const budgetEfforts: ReadonlyArray<Effort> = ["low", "medium", "high", "xhigh", "max"];

/**
 * Returns the efforts that a model with `capabilities` takes, least first, other than `none`: those
 * models.dev lists; `budgetEfforts` for a model that takes a thinking budget instead; none for a
 * model that does not reason; undefined when that is not known.
 */
export const effortsTaken = (capabilities: Capabilities | undefined): ReadonlyArray<Effort> | undefined => {
  if (capabilities === undefined) return undefined;
  if (capabilities.efforts !== undefined) return capabilities.efforts.filter((effort): effort is Effort => effort !== "none");
  if (capabilities.budget !== undefined) return budgetEfforts;
  return capabilities.reasoning === false ? [] : undefined;
};

/**
 * Returns whether a model with `capabilities` can turn its thinking off: its efforts list `none`, or
 * it takes a thinking budget (its thinking is off unless a budget turns it on). A model that does
 * not reason cannot. Undefined when that is not known.
 */
export const turnsThinkingOff = (capabilities: Capabilities | undefined): boolean | undefined => {
  if (capabilities === undefined) return undefined;
  if (capabilities.budget !== undefined) return true;
  if (capabilities.efforts !== undefined) return capabilities.efforts.includes("none");
  return capabilities.reasoning === false ? false : undefined;
};

/** Returns what is known of the model that a request goes to: what its target carries, or the well-known model's entry. */
export const knownOf = (target: { readonly provider: ProviderName; readonly model: ModelName; readonly capabilities?: Capabilities }): Capabilities | undefined =>
  target.capabilities ?? capabilitiesOf(target.provider, target.model);

/**
 * Whether a model with `capabilities` accepts a file of `mediaType` as input: an image (`image/*`) or
 * a PDF, when it lists that kind. A model of which nothing is known is treated as accepting neither.
 */
export function takesFile(capabilities: Capabilities | undefined, mediaType: string): boolean {
  const kinds = capabilities?.input ?? [];
  return (mediaType.startsWith("image/") && kinds.includes("image")) || (mediaType === "application/pdf" && kinds.includes("pdf"));
}

type WellKnown = typeof wellKnownModels;

/** A provider with well-known models, and a well-known model of it. */
export type WellKnownProvider = keyof WellKnown;
export type WellKnownModel<P extends WellKnownProvider> = keyof WellKnown[P];

/** Whether a well-known model takes a thinking budget. */
type TakesBudget<P extends WellKnownProvider, M extends WellKnownModel<P>> = WellKnown[P][M] extends { readonly budget: unknown } ? true : false;

/** The reasoning efforts that a well-known model accepts, as models.dev lists them: the budget efforts for a model that takes a budget instead (`budgetEfforts`); any effort where neither is listed. */
type EffortsOf<P extends WellKnownProvider, M extends WellKnownModel<P>> =
  WellKnown[P][M] extends { readonly efforts: ReadonlyArray<infer Taken> } ? Taken : TakesBudget<P, M> extends true ? Exclude<Effort, "minimal"> : string;

/** The thinking modes that a well-known model takes: `disabled` where it can turn its thinking off, and the modes measured for it. */
type ThinkingOf<P extends WellKnownProvider, M extends WellKnownModel<P>> =
  | ("none" extends EffortsOf<P, M> ? "disabled" : TakesBudget<P, M> extends true ? "disabled" : never)
  | (WellKnown[P][M] extends { readonly thinking: ReadonlyArray<infer Measured> } ? Extract<ThinkingMode, Measured> : never);

/**
 * A session's settings for a well-known model: the efforts that it accepts, thinking `disabled`
 * only where it can turn its thinking off, and the thinking modes measured for it. A UI bound to
 * this type offers only what the model accepts.
 */
export type SettingsFor<P extends WellKnownProvider, M extends WellKnownModel<P>> = Omit<ModelSettings, "effort" | "thinking"> & {
  readonly effort?: Extract<Effort, EffortsOf<P, M>>;
  readonly thinking?: ThinkingOf<P, M>;
};
