/**
 * The well-known models: what is known of each (`Capabilities`), and a model's settings as a type.
 *
 * The data is `well-known-models.gen.ts`, generated by `bun scripts/models/refresh.ts` from two
 * sources. models.dev's catalog gives each model's context window, output limit, kinds of input
 * and price in US dollars per million tokens (`above` is the price of a request whose input is over
 * its `context`). `well-known-models.measured.json` names the models and holds what was measured
 * against the providers (2026-10-01) and is not in the catalog, or differs from it:
 *
 * - the reasoning efforts each OpenAI and xAI model takes (each was asked every effort);
 * - PDF input for ten GPT-5 models the catalog lists as taking none (each read one when sent it);
 * - Anthropic's hour-long cache writes, at twice the input price (the catalog has the five-minute rate).
 *
 * Also measured: Anthropic refuses `max_tokens` above a model's output (Haiku 4.5: 64,000); OpenAI
 * accepts any `max_output_tokens`, so its limit cannot be read from a refusal.
 *
 * A model is found by its name or by its name with a release date after it
 * (`claude-haiku-4-5-20251001` is `claude-haiku-4-5`; `gpt-5-mini` is not `gpt-5`). A model that is
 * not well-known (a local server's) is known by what its host provides (`KnownModels`), at run time.
 */

import { Context, Effect } from "effect";
import type { ModelName, ProviderName } from "../../agent-machine/names.ts";
import type { Effort, ModelSettings, ThinkingMode } from "../../agent-machine/settings.ts";
import { firstAnswer } from "../first-answer.ts";
import { wellKnownModels } from "./well-known-models.gen.ts";

export interface Price {
  readonly input: number;
  readonly output: number;
  readonly cacheRead?: number;
  readonly cacheWrite?: number;
  readonly cacheWrite1h?: number;
}

/**
 * What is known of a model: what it takes and what it costs. A request is shaped to it: a setting
 * outside what the model takes is sent as the nearest it does (an effort above its highest, as its
 * highest).
 */
export interface Capabilities {
  /** The most tokens of context the model takes, when known. */
  readonly context?: number;
  /** The most tokens the model writes in one response, when known. */
  readonly output?: number;
  /** The kinds of input it takes: `text`, `image`, `pdf`. */
  readonly input: ReadonlyArray<string>;
  /** The reasoning efforts it takes, least first, when known. */
  readonly efforts?: ReadonlyArray<string>;
  readonly price: Price & { readonly above?: Price & { readonly context: number } };
}

const known: Readonly<Record<string, Readonly<Record<string, Capabilities>>>> = wellKnownModels;

/** `model` is `name` with its release date after it: `-2025-08-07` (OpenAI) or `-20251001` (Anthropic). */
const datedFrom = (name: string, model: string): boolean =>
  model.startsWith(`${name}-`) && /^(\d{4}-\d{2}-\d{2}|\d{8})$/.test(model.slice(name.length + 1));

/** What is known of the well-known `model` of `provider`, found by its name or a dated name. */
export function capabilitiesOf(provider: ProviderName | string, model: ModelName | string): Capabilities | undefined {
  const models = known[provider] ?? {};
  const name = model in models ? model : Object.keys(models).find((each) => datedFrom(each, model));
  return name === undefined ? undefined : models[name];
}

/** What one source knows of a model: its capabilities, or `undefined` when it does not know it. */
export type ModelKnowledge = (provider: ProviderName, model: ModelName) => Effect.Effect<Capabilities | undefined>;

/** The well-known models. */
export const wellKnown: ModelKnowledge = (provider, model) => Effect.succeed(capabilitiesOf(provider, model));

/**
 * What is known of each model, for whoever chooses the model for a request (`ModelFromFacts` puts
 * it on the request's target): sources asked in order, the first that knows a model answering
 * (`firstAnswer`). By default the well-known models; a host that knows more (a local server that
 * says what its models take) puts its source in front.
 */
export const KnownModels = Context.Reference<ReadonlyArray<ModelKnowledge>>("agent-session/KnownModels", { defaultValue: () => [wellKnown] });

/** What is known of `model` of `provider`: the first answer of `KnownModels`. */
export const knownCapabilities = (provider: ProviderName, model: ModelName): Effect.Effect<Capabilities | undefined> =>
  Effect.gen(function* () {
    const sources = yield* KnownModels;
    return yield* firstAnswer(sources.map((source) => source(provider, model)));
  });

/** What is known of the model a request goes to: what its target carries, or the well-known model's. */
export const knownOf = (target: { readonly provider: ProviderName; readonly model: ModelName; readonly capabilities?: Capabilities }): Capabilities | undefined =>
  target.capabilities ?? capabilitiesOf(target.provider, target.model);

/**
 * Whether a model with `capabilities` takes a file of `mediaType` as input: an image (`image/*`) or
 * a PDF when it lists the kind. A model nothing is known of is not known to take either.
 */
export function takesFile(capabilities: Capabilities | undefined, mediaType: string): boolean {
  const kinds = capabilities?.input ?? [];
  return (mediaType.startsWith("image/") && kinds.includes("image")) || (mediaType === "application/pdf" && kinds.includes("pdf"));
}

type WellKnown = typeof wellKnownModels;

/** A provider with well-known models, and a well-known model of it. */
export type WellKnownProvider = keyof WellKnown;
export type WellKnownModel<P extends WellKnownProvider> = keyof WellKnown[P];

/** The reasoning efforts a well-known model takes, as measured; where none were, any. */
type EffortsOf<P extends WellKnownProvider, M extends WellKnownModel<P>> = WellKnown[P][M] extends { readonly efforts: ReadonlyArray<infer Taken> } ? Taken : string;

/**
 * A session's settings for a well-known model: the efforts it takes, and thinking `off` only where
 * it takes effort `none`. A UI bound to this type offers what the model takes.
 */
export type SettingsFor<P extends WellKnownProvider, M extends WellKnownModel<P>> = Omit<ModelSettings, "effort" | "thinking"> & {
  readonly effort?: Extract<Effort, EffortsOf<P, M>>;
  readonly thinking?: "none" extends EffortsOf<P, M> ? ThinkingMode : Exclude<ThinkingMode, "off">;
};
