// Generated by scripts/acp-schema.ts from @agentclientprotocol/sdk 1.5.0 schema/schema.json (ACP protocol version 1).
// Do not edit: run `bun run acp:schema`.

import { Rpc, RpcGroup } from "effect/rpc";
import { JsonRpcError } from "../json-rpc.ts";
import * as Schemas from "./v1.gen.ts";

/** The requests the agent serves. */
export const AgentRequests = RpcGroup.make(
  Rpc.make("authenticate", { payload: Schemas.AuthenticateRequest, success: Schemas.AuthenticateResponse, error: JsonRpcError }),
  Rpc.make("initialize", { payload: Schemas.InitializeRequest, success: Schemas.InitializeResponse, error: JsonRpcError }),
  Rpc.make("logout", { payload: Schemas.LogoutRequest, success: Schemas.LogoutResponse, error: JsonRpcError }),
  Rpc.make("mcp/message", { payload: Schemas.MessageMcpRequest, success: Schemas.MessageMcpResponse, error: JsonRpcError }),
  Rpc.make("nes/close", { payload: Schemas.CloseNesRequest, success: Schemas.CloseNesResponse, error: JsonRpcError }),
  Rpc.make("nes/start", { payload: Schemas.StartNesRequest, success: Schemas.StartNesResponse, error: JsonRpcError }),
  Rpc.make("nes/suggest", { payload: Schemas.SuggestNesRequest, success: Schemas.SuggestNesResponse, error: JsonRpcError }),
  Rpc.make("providers/disable", { payload: Schemas.DisableProviderRequest, success: Schemas.DisableProviderResponse, error: JsonRpcError }),
  Rpc.make("providers/list", { payload: Schemas.ListProvidersRequest, success: Schemas.ListProvidersResponse, error: JsonRpcError }),
  Rpc.make("providers/set", { payload: Schemas.SetProviderRequest, success: Schemas.SetProviderResponse, error: JsonRpcError }),
  Rpc.make("session/close", { payload: Schemas.CloseSessionRequest, success: Schemas.CloseSessionResponse, error: JsonRpcError }),
  Rpc.make("session/delete", { payload: Schemas.DeleteSessionRequest, success: Schemas.DeleteSessionResponse, error: JsonRpcError }),
  Rpc.make("session/fork", { payload: Schemas.ForkSessionRequest, success: Schemas.ForkSessionResponse, error: JsonRpcError }),
  Rpc.make("session/list", { payload: Schemas.ListSessionsRequest, success: Schemas.ListSessionsResponse, error: JsonRpcError }),
  Rpc.make("session/load", { payload: Schemas.LoadSessionRequest, success: Schemas.LoadSessionResponse, error: JsonRpcError }),
  Rpc.make("session/new", { payload: Schemas.NewSessionRequest, success: Schemas.NewSessionResponse, error: JsonRpcError }),
  Rpc.make("session/prompt", { payload: Schemas.PromptRequest, success: Schemas.PromptResponse, error: JsonRpcError }),
  Rpc.make("session/resume", { payload: Schemas.ResumeSessionRequest, success: Schemas.ResumeSessionResponse, error: JsonRpcError }),
  Rpc.make("session/set_config_option", { payload: Schemas.SetSessionConfigOptionRequest, success: Schemas.SetSessionConfigOptionResponse, error: JsonRpcError }),
  Rpc.make("session/set_mode", { payload: Schemas.SetSessionModeRequest, success: Schemas.SetSessionModeResponse, error: JsonRpcError }),
);

/** The notifications the agent receives. */
export const AgentNotifications = RpcGroup.make(
  Rpc.make("document/didChange", { payload: Schemas.DidChangeDocumentNotification }),
  Rpc.make("document/didClose", { payload: Schemas.DidCloseDocumentNotification }),
  Rpc.make("document/didFocus", { payload: Schemas.DidFocusDocumentNotification }),
  Rpc.make("document/didOpen", { payload: Schemas.DidOpenDocumentNotification }),
  Rpc.make("document/didSave", { payload: Schemas.DidSaveDocumentNotification }),
  Rpc.make("mcp/message", { payload: Schemas.MessageMcpNotification }),
  Rpc.make("nes/accept", { payload: Schemas.AcceptNesNotification }),
  Rpc.make("nes/reject", { payload: Schemas.RejectNesNotification }),
  Rpc.make("session/cancel", { payload: Schemas.CancelNotification }),
);

/** The requests the client serves. */
export const ClientRequests = RpcGroup.make(
  Rpc.make("elicitation/create", { payload: Schemas.CreateElicitationRequest, success: Schemas.CreateElicitationResponse, error: JsonRpcError }),
  Rpc.make("fs/read_text_file", { payload: Schemas.ReadTextFileRequest, success: Schemas.ReadTextFileResponse, error: JsonRpcError }),
  Rpc.make("fs/write_text_file", { payload: Schemas.WriteTextFileRequest, success: Schemas.WriteTextFileResponse, error: JsonRpcError }),
  Rpc.make("mcp/connect", { payload: Schemas.ConnectMcpRequest, success: Schemas.ConnectMcpResponse, error: JsonRpcError }),
  Rpc.make("mcp/disconnect", { payload: Schemas.DisconnectMcpRequest, success: Schemas.DisconnectMcpResponse, error: JsonRpcError }),
  Rpc.make("mcp/message", { payload: Schemas.MessageMcpRequest, success: Schemas.MessageMcpResponse, error: JsonRpcError }),
  Rpc.make("session/request_permission", { payload: Schemas.RequestPermissionRequest, success: Schemas.RequestPermissionResponse, error: JsonRpcError }),
  Rpc.make("terminal/create", { payload: Schemas.CreateTerminalRequest, success: Schemas.CreateTerminalResponse, error: JsonRpcError }),
  Rpc.make("terminal/kill", { payload: Schemas.KillTerminalRequest, success: Schemas.KillTerminalResponse, error: JsonRpcError }),
  Rpc.make("terminal/output", { payload: Schemas.TerminalOutputRequest, success: Schemas.TerminalOutputResponse, error: JsonRpcError }),
  Rpc.make("terminal/release", { payload: Schemas.ReleaseTerminalRequest, success: Schemas.ReleaseTerminalResponse, error: JsonRpcError }),
  Rpc.make("terminal/wait_for_exit", { payload: Schemas.WaitForTerminalExitRequest, success: Schemas.WaitForTerminalExitResponse, error: JsonRpcError }),
);

/** The notifications the client receives. */
export const ClientNotifications = RpcGroup.make(
  Rpc.make("elicitation/complete", { payload: Schemas.CompleteElicitationNotification }),
  Rpc.make("mcp/message", { payload: Schemas.MessageMcpNotification }),
  Rpc.make("session/update", { payload: Schemas.SessionNotification }),
);

/** The methods whose definitions are marked **UNSTABLE**: not part of the spec yet, and may change or go. */
export const unstable: ReadonlySet<string> = new Set(["mcp/connect", "mcp/disconnect", "mcp/message", "providers/disable", "providers/list", "providers/set", "session/fork"]);
