// Generated by scripts/acp-schema.ts from @agentclientprotocol/sdk 1.5.0 schema/v2/schema.unstable.json (ACP protocol version 2).
// Do not edit: run `bun run acp:schema`.

import * as Methods from "../methods.ts";
import * as Schemas from "./v2.gen.ts";

/** The requests the agent serves. */
export const AgentRequests = Methods.make(
  Methods.request("auth/login", Schemas.LoginAuthRequest, Schemas.LoginAuthResponse),
  Methods.request("auth/logout", Schemas.LogoutAuthRequest, Schemas.LogoutAuthResponse),
  Methods.request("initialize", Schemas.InitializeRequest, Schemas.InitializeResponse),
  Methods.request("mcp/message", Schemas.MessageMcpRequest, Schemas.MessageMcpResponse),
  Methods.request("nes/close", Schemas.CloseNesRequest, Schemas.CloseNesResponse),
  Methods.request("nes/start", Schemas.StartNesRequest, Schemas.StartNesResponse),
  Methods.request("nes/suggest", Schemas.SuggestNesRequest, Schemas.SuggestNesResponse),
  Methods.request("providers/disable", Schemas.DisableProviderRequest, Schemas.DisableProviderResponse),
  Methods.request("providers/list", Schemas.ListProvidersRequest, Schemas.ListProvidersResponse),
  Methods.request("providers/set", Schemas.SetProviderRequest, Schemas.SetProviderResponse),
  Methods.request("session/close", Schemas.CloseSessionRequest, Schemas.CloseSessionResponse),
  Methods.request("session/delete", Schemas.DeleteSessionRequest, Schemas.DeleteSessionResponse),
  Methods.request("session/fork", Schemas.ForkSessionRequest, Schemas.ForkSessionResponse),
  Methods.request("session/list", Schemas.ListSessionsRequest, Schemas.ListSessionsResponse),
  Methods.request("session/new", Schemas.NewSessionRequest, Schemas.NewSessionResponse),
  Methods.request("session/prompt", Schemas.PromptRequest, Schemas.PromptResponse),
  Methods.request("session/resume", Schemas.ResumeSessionRequest, Schemas.ResumeSessionResponse),
  Methods.request("session/set_config_option", Schemas.SetSessionConfigOptionRequest, Schemas.SetSessionConfigOptionResponse),
);

/** The notifications the agent receives. */
export const AgentNotifications = Methods.make(
  Methods.notification("document/didChange", Schemas.DidChangeDocumentNotification),
  Methods.notification("document/didClose", Schemas.DidCloseDocumentNotification),
  Methods.notification("document/didFocus", Schemas.DidFocusDocumentNotification),
  Methods.notification("document/didOpen", Schemas.DidOpenDocumentNotification),
  Methods.notification("document/didSave", Schemas.DidSaveDocumentNotification),
  Methods.notification("mcp/message", Schemas.MessageMcpNotification),
  Methods.notification("nes/accept", Schemas.AcceptNesNotification),
  Methods.notification("nes/reject", Schemas.RejectNesNotification),
  Methods.notification("session/cancel", Schemas.CancelSessionNotification),
);

/** The requests the client serves. */
export const ClientRequests = Methods.make(
  Methods.request("elicitation/create", Schemas.CreateElicitationRequest, Schemas.CreateElicitationResponse),
  Methods.request("mcp/connect", Schemas.ConnectMcpRequest, Schemas.ConnectMcpResponse),
  Methods.request("mcp/disconnect", Schemas.DisconnectMcpRequest, Schemas.DisconnectMcpResponse),
  Methods.request("mcp/message", Schemas.MessageMcpRequest, Schemas.MessageMcpResponse),
  Methods.request("session/request_permission", Schemas.RequestPermissionRequest, Schemas.RequestPermissionResponse),
);

/** The notifications the client receives. */
export const ClientNotifications = Methods.make(
  Methods.notification("elicitation/complete", Schemas.CompleteElicitationNotification),
  Methods.notification("mcp/message", Schemas.MessageMcpNotification),
  Methods.notification("session/update", Schemas.UpdateSessionNotification),
);

/** The methods whose definitions are marked **UNSTABLE**: not part of the spec yet, and may change or go. */
export const unstable: ReadonlySet<string> = new Set(["mcp/connect", "mcp/disconnect", "mcp/message", "providers/disable", "providers/list", "providers/set", "session/fork"]);
